# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1-status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1-status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv1-status.proto\x12\tv1.status\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n\rStatusRequest\"\xc2\x01\n\x0bStatusReply\x12)\n\x04\x64\x61ta\x18\n \x01(\x0b\x32\x1b.v1.status.StatusReply.Data\x1a\x87\x01\n\x04\x44\x61ta\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x32\n\x0f\x62uild_variables\x18\x02 \x01(\x0b\x32\x19.v1.status.BuildVariables\x12&\n\x06probes\x18\x03 \x03(\x0b\x32\x16.v1.status.StatusProbe\x12\x0e\n\x06status\x18\x04 \x01(\t\"\x17\n\tBeatReply\x12\n\n\x02OK\x18\x01 \x01(\x08\"p\n\x0bStatusProbe\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x31\n\rlastCheckedTS\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x97\x01\n\x0e\x42uildVariables\x12\x12\n\ngit_commit\x18\x01 \x01(\t\x12\x12\n\ngit_branch\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x12\n\ngo_version\x18\x04 \x01(\t\x12\x0f\n\x07go_arch\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x14\n\x0cservice_name\x18\x07 \x01(\t\"q\n\x10StatusProbeStore\x12-\n\tnextCheck\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\x0epreviousResult\x18\x02 \x01(\x0b\x32\x16.v1.status.StatusProbe2E\n\tHeartbeat\x12\x38\n\x04\x42\x65\x61t\x12\x18.v1.status.StatusRequest\x1a\x14.v1.status.BeatReply\"\x00\x42\'Z%eduseal/internal/gen/status/v1_statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%eduseal/internal/gen/status/v1_status'
  _globals['_STATUSREQUEST']._serialized_start=63
  _globals['_STATUSREQUEST']._serialized_end=78
  _globals['_STATUSREPLY']._serialized_start=81
  _globals['_STATUSREPLY']._serialized_end=275
  _globals['_STATUSREPLY_DATA']._serialized_start=140
  _globals['_STATUSREPLY_DATA']._serialized_end=275
  _globals['_BEATREPLY']._serialized_start=277
  _globals['_BEATREPLY']._serialized_end=300
  _globals['_STATUSPROBE']._serialized_start=302
  _globals['_STATUSPROBE']._serialized_end=414
  _globals['_BUILDVARIABLES']._serialized_start=417
  _globals['_BUILDVARIABLES']._serialized_end=568
  _globals['_STATUSPROBESTORE']._serialized_start=570
  _globals['_STATUSPROBESTORE']._serialized_end=683
  _globals['_HEARTBEAT']._serialized_start=685
  _globals['_HEARTBEAT']._serialized_end=754
# @@protoc_insertion_point(module_scope)
