# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1-sealer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv1-sealer.proto\x12\tv1.sealer\"2\n\x0bSealRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0b\n\x03pdf\x18\x02 \x01(\t\"h\n\tSealReply\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0b\n\x03pdf\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x11\n\tcreate_ts\x18\x05 \x01(\x03\x32@\n\x06Sealer\x12\x36\n\x04Seal\x12\x16.v1.sealer.SealRequest\x1a\x14.v1.sealer.SealReply\"\x00\x42\'Z%eduseal/internal/gen/sealer/v1_sealerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1_sealer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%eduseal/internal/gen/sealer/v1_sealer'
  _globals['_SEALREQUEST']._serialized_start=30
  _globals['_SEALREQUEST']._serialized_end=80
  _globals['_SEALREPLY']._serialized_start=82
  _globals['_SEALREPLY']._serialized_end=186
  _globals['_SEALER']._serialized_start=188
  _globals['_SEALER']._serialized_end=252
# @@protoc_insertion_point(module_scope)
