---
common:
  mongo:
    uri: mongodb://mongo:27017
    disable: true
  production: false
  tracing:
    addr: jaeger:4318
    type: jaeger
  etcd:
    addresses: 
      - http://etcd1:2379
      - http://etcd2:2379
      - http://etcd3:2379
      - http://etcd4:2379
      - http://etcd5:2379
    #username: "test-username"
    password: test-password
  sealer_grpc_hosts:
    - sealer_1:50051
    - sealer_2:50051
  validator_grpc_hosts: 
    - validator_1:50051
    - validator_2:50051

cache:
  api_server:
    addr: :8080

persistent:
  api_server:
    addr: :8080

apigw:
  api_server:
    addr: :8080
  jwt_auth:
    enabled: false
    access:
      "860223": eduseal-test

sealer_1:
  pkcs11:
    pin: "1234"
    module: /usr/lib/softhsm/libsofthsm2.so
    label: test_label
    key_label: test_key_label
    cert_label: test_cert_label
    #slot: 0
  metadata:
    location: "Stockholm"
    reason: "Future validation"
    name: "SUNET/Vetenskapsrådet"
    contact_info: "info@sunet.se"
    field_name: "Signature1"

sealer_2:
  pkcs11:
    pin: "1234"
    module: /usr/lib/softhsm/libsofthsm2.so
    label: test_label
    key_label: test_key_label
    cert_label: test_cert_label
    #slot: 0
  metadata:
    location: "Stockholm"
    reason: "Future validation"
    name: "SUNET/Vetenskapsrådet"
    contact_info: "info@sunet.se"
    field_name: "Signature1"

validator_1:
  validation_certificates_path: "/validation_certificates"

validator_2:
  validation_certificates_path: "/validation_certificates"