---

services:
  apigw:
    container_name: "eduseal_dev_apigw"
    image: docker.sunet.se/eduseal/apigw:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
      - ./developer_tools/pki/rootCA.crt:/etc/ssl/certs/eduseal_root_CA.crt:ro
      - ./developer_tools/pki/apigw.crt:/etc/ssl/certs/apigw.crt:ro
      - ./developer_tools/pki/apigw.key:/etc/ssl/private/apigw.key:ro
      - ./developer_tools/pki/apigw.pem:/etc/ssl/private/apigw.pem:ro
    depends_on:
      #- mongo
      - validator_1
      - validator_2
      - nats1
      - nats2
      - nats3
      - jaeger
    links:
      - validator_1
      - validator_2
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.200
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"
      - "EDUSEAL_SERVICE_NAME=apigw"
    # - "GRPC_GO_LOG_VERBOSITY_LEVEL=99"
    # - "GRPC_GO_LOG_SEVERITY_LEVEL=info"

  sealer_1:
    container_name: "eduseal_dev_sealer_1"
    image: docker.sunet.se/eduseal/sealer_softhsm:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
      - ./developer_tools/pki/sealer_1.key:/etc/ssl/private/sealer_1.key:ro
      - ./developer_tools/pki/sealer_1.pem:/etc/ssl/private/sealer_1.pem:ro
      - ./developer_tools/pki/rootCA.crt:/etc/ssl/certs/eduseal_root_CA.crt:ro
      - ./developer_tools/pki/document_sealing_private.der:/opt/sunet/pki/sealing.der:ro
      - ./developer_tools/pki/document_sealing.crt:/opt/sunet/pki/sealing.crt:ro
    expose:
      - 50051
    depends_on:
      - nats1
      - nats2
      - nats3
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.14
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"
      - "EDUSEAL_SERVICE_NAME=sealer_1"
      - "EDUSEAL_CONFIG_NAMESPACE=sealer_1"

  sealer_2:
    container_name: "eduseal_dev_sealer_2"
    image: docker.sunet.se/eduseal/sealer_softhsm:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
      - ./developer_tools/pki/sealer_2.key:/etc/ssl/private/sealer_2.key:ro
      - ./developer_tools/pki/sealer_2.pem:/etc/ssl/private/sealer_2.pem:ro
      - ./developer_tools/pki/rootCA.crt:/etc/ssl/certs/eduseal_root_CA.crt:ro
      - ./developer_tools/pki/document_sealing_private.der:/opt/sunet/pki/sealing.der:ro
      - ./developer_tools/pki/document_sealing.crt:/opt/sunet/pki/sealing.crt:ro
    depends_on:
      - nats1
      - nats2
      - nats3
    expose:
      - 50051
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.15
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"
      - "EDUSEAL_SERVICE_NAME=sealer_2"
      - "EDUSEAL_CONFIG_NAMESPACE=sealer_2"

  validator_1:
    container_name: "eduseal_dev_validator_1"
    image: docker.sunet.se/eduseal/validator_grpc:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
      - ./developer_tools/pki/validator_1.key:/etc/ssl/private/validator_1.key:ro
      - ./developer_tools/pki/validator_1.pem:/etc/ssl/private/validator_1.pem:ro
      - ./developer_tools/pki/rootCA.crt:/validation_certificates/rootCA.crt:ro
    expose:
      - 50051
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.16
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"
      - "EDUSEAL_SERVICE_NAME=validator_1"
      - "EDUSEAL_CONFIG_NAMESPACE=validator_1"

  validator_2:
    container_name: "eduseal_dev_validator_2"
    image: docker.sunet.se/eduseal/validator_grpc:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
      - ./developer_tools/pki/validator_2.key:/etc/ssl/private/validator_2.key:ro
      - ./developer_tools/pki/validator_2.pem:/etc/ssl/private/validator_2.pem:ro
      - ./developer_tools/pki/rootCA.crt:/validation_certificates/rootCA.crt:ro
    expose:
      - 50051
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.17
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"
      - "EDUSEAL_SERVICE_NAME=validator_2"
      - "EDUSEAL_CONFIG_NAMESPACE=validator_2"

  redis-node-0:
    container_name: "eduseal_dev_redis-node-0"
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.30
    environment:
      - 'REDIS_PASSWORD=test-password'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-1:
    container_name: "eduseal_dev_redis-node-1"
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.31
    environment:
      - 'REDIS_PASSWORD=test-password'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    container_name: "eduseal_dev_redis-node-2"
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.32
    environment:
      - 'REDIS_PASSWORD=test-password'
      - 'REDISCLI_AUTH=test-password'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'

  nats1:
    image: docker.io/nats:linux
    container_name: "eduseal_dev_nats1"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats1:/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.41
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://nats1:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats2:
    image: docker.io/nats:linux
    container_name: "eduseal_dev_nats2"
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - nats2:/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.42
    command:
      - "--name=nats2"
      - "--cluster_name=c1"
      - "--cluster=nats://nats2:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats3:
    image: docker.io/nats:linux
    container_name: "eduseal_dev_nats3"
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - nats3:/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.43
    command:
      - "--name=nats3"
      - "--cluster_name=c1"
      - "--cluster=nats://nats3:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  #  image: mongo:4.0.10
  #  container_name: "eduseal_dev_mongo"
  #  restart: always
  #  expose:
  #    - 27017
  #  volumes:
  #    - mongo_data:/data
  #  networks:
  #    eduseal-dev-net:
  #      ipv4_address: 172.20.50.26

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: eduseal_dev_jaeger
    restart: always
    expose:
      - 16686
      - 4317
      - 4318
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.50
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"

networks:
  eduseal-dev-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduseal-dev
    ipam:
      driver: default
      config:
        - subnet: 172.20.50.0/24
volumes:
  mongo_data:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  nats1:
    external: true
  nats2:
    external: true
  nats3:
    external: true
  prometheus_data:
  grafana_data:
