---
version: "3"

services:
  apigw:
    container_name: "eduseal_dev_apigw"
    image: docker.sunet.se/eduseal/apigw:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
    depends_on:
      - redis
      - mongo
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.2
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"

  cache:
    container_name: "eduseal_dev_cache"
    image: docker.sunet.se/eduseal/cache:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
    depends_on:
      - redis
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.10
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"

  persistent:
    container_name: "eduseal_dev_persistent"
    image: docker.sunet.se/eduseal/persistent:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
    depends_on:
      - redis
      - mongo
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.12
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"

  sealer_1:
    container_name: "eduseal_dev_sealer_1"
    image: docker.sunet.se/eduseal/sealer_softhsm_grpc:latest
    restart: always
    volumes:
      - ./config.yaml:/config.yaml:ro
      - /var/log/sunet:/var/log/sunet
    depends_on:
      - redis
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.14
    environment:
      - "EDUSEAL_CONFIG_YAML=config.yaml"

  #sealer_2:
  #  container_name: "eduseal_dev_sealer_2"
  #  image: docker.sunet.se/eduseal/sealer_softhsm_gprc:latest
  #  restart: always
  #  volumes:
  #    - ./config.yaml:/config.yaml:ro
  #    - /var/log/sunet:/var/log/sunet
  #  depends_on:
  #    - redis
  #  networks:
  #    eduseal-dev-net:
  #      ipv4_address: 172.20.50.15
  #  environment:
  #    - "EDUSEAL_CONFIG_YAML=config.yaml"

  #validator_1:
  #  container_name: "eduseal_dev_validator_1"
  #  image: docker.sunet.se/eduseal/validator_grpc:latest
  #  restart: always
  #  volumes:
  #    - ./config.yaml:/config.yaml:ro
  #    - /var/log/sunet:/var/log/sunet
  #    - ./validation_certificates/softhsm:/validation_certificates:ro
  #  depends_on:
  #    - redis
  #  networks:
  #    eduseal-dev-net:
  #      ipv4_address: 172.20.50.16
  #  environment:
  #    - "EDUSEAL_CONFIG_YAML=config.yaml"

  #validator_2:
  #  container_name: "eduseal_dev_validator_2"
  #  image: docker.sunet.se/eduseal/validator_grpc:latest
  #  restart: always
  #  volumes:
  #    - ./config.yaml:/config.yaml:ro
  #    - /var/log/sunet:/var/log/sunet
  #    - ./validation_certificates/softhsm:/validation_certificates:ro
  #  depends_on:
  #    - redis
  #  networks:
  #    eduseal-dev-net:
  #      ipv4_address: 172.20.50.17
  #  environment:
  #    - "EDUSEAL_CONFIG_YAML=config.yaml"

  redis:
    image: redis:alpine
    container_name: "eduseal_dev_redis"
    restart: always
    expose:
      - 6373
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.18

  mongo:
    image: mongo:4.0.10
    container_name: "eduseal_dev_mongo"
    restart: always
    expose:
      - 27017
    volumes:
      - mongo_data:/data
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.20

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: eduseal_dev_jaeger
    restart: always
    expose:
      - 16686
      - 4317
      - 4318
    networks:
      eduseal-dev-net:
        ipv4_address: 172.20.50.22
    environment:
      - "COLLECTOR_OTLP_ENABLED=true"

networks:
  eduseal-dev-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduseal-dev
    ipam:
      driver: default
      config:
        - subnet: 172.20.50.0/24
volumes:
  redis_data:
  mongo_data:
