oauth:
  access_token:
    - flags:
        - bearer
      access:
        - type: eduseal
  client:
    key: masv_test_3

env: test
testcase: ladok
save: true
client_cert: ./client.cert
client_cert_key: ./client.key
pdf_size: small  # Options: small, medium, big
