# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1-validator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12v1-validator.proto\x12\x0cv1.validator\"\x1e\n\x0fValidateRequest\x12\x0b\n\x03pdf\x18\x01 \x01(\t\"\x7f\n\rValidateReply\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x18\n\x10intact_signature\x18\x02 \x01(\x08\x12\x17\n\x0fvalid_signature\x18\x03 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t2U\n\tValidator\x12H\n\x08Validate\x12\x1d.v1.validator.ValidateRequest\x1a\x1b.v1.validator.ValidateReply\"\x00\x42-Z+eduseal/internal/gen/validator/v1_validatorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1_validator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+eduseal/internal/gen/validator/v1_validator'
  _globals['_VALIDATEREQUEST']._serialized_start=36
  _globals['_VALIDATEREQUEST']._serialized_end=66
  _globals['_VALIDATEREPLY']._serialized_start=68
  _globals['_VALIDATEREPLY']._serialized_end=195
  _globals['_VALIDATOR']._serialized_start=197
  _globals['_VALIDATOR']._serialized_end=282
# @@protoc_insertion_point(module_scope)
