// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pdf/sign": {
            "post": {
                "description": "seal base64 encoded PDF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EduSeal"
                ],
                "summary": "Seal pdf",
                "operationId": "pdf-seal",
                "parameters": [
                    {
                        "description": " ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiv1.PDFSignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/apiv1.PDFSignReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pdf/validate": {
            "post": {
                "description": "validate a sealed base64 encoded PDF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EduSeal"
                ],
                "summary": "Validate pdf",
                "operationId": "pdf-validate",
                "parameters": [
                    {
                        "description": " ",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiv1.PDFValidateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/apiv1.PDFValidateReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/pdf/{transaction_id}": {
            "get": {
                "description": "fetch a sealed pdf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EduSeal"
                ],
                "summary": "fetch sealed pdf",
                "operationId": "pdf-fetch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "transaction_id",
                        "name": "transaction_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/apiv1.PDFGetSignedReply"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiv1.PDFGetSignedReply": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Document"
                }
            }
        },
        "apiv1.PDFSignReply": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/v1_sealer.SealReply"
                }
            }
        },
        "apiv1.PDFSignRequest": {
            "type": "object",
            "required": [
                "pdf"
            ],
            "properties": {
                "pdf": {
                    "type": "string"
                }
            }
        },
        "apiv1.PDFValidateReply": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/v1_validator.ValidateReply"
                }
            }
        },
        "apiv1.PDFValidateRequest": {
            "type": "object",
            "properties": {
                "pdf": {
                    "type": "string"
                }
            }
        },
        "helpers.Error": {
            "type": "object",
            "properties": {
                "details": {},
                "title": {
                    "type": "string"
                }
            }
        },
        "helpers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/helpers.Error"
                }
            }
        },
        "model.Document": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "integer"
                },
                "sealer_backend": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "v1_sealer.SealReply": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "sealer_backend": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "v1_validator.ValidateReply": {
            "type": "object",
            "properties": {
                "coverage": {
                    "description": "coverage indicates how much of the file is covered by the signed byte\nrange. Values match pyHanko's SignatureCoverageLevel names\n(UNCLEAR, CONTIGUOUS_BLOCK_FROM_START, ENTIRE_REVISION, ENTIRE_FILE).",
                    "type": "string"
                },
                "docmdp_ok": {
                    "description": "docmdp_ok reports whether the certification-policy (DocMDP) check\nsucceeded. False indicates disallowed modifications were made after\nthe document was sealed.",
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "intact_signature": {
                    "description": "intact_signature is true iff the cryptographic signature is intact AND\nthe signature covers the entire file (no post-signature bytes appended).",
                    "type": "boolean"
                },
                "modification_level": {
                    "description": "modification_level reports the severity of modifications made after\nsigning. Values match pyHanko's ModificationLevel names\n(NONE, LTA_UPDATES, FORM_FILLING, ANNOTATIONS, OTHER).",
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "valid_signature": {
                    "description": "valid_signature is true iff the signature passes pyHanko's overall\ntrust judgment (bottom_line): signer chain trusted, DocMDP policy\nsatisfied and no disallowed modifications were made after signing.",
                    "type": "boolean"
                },
                "validation_backend": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EduSeal API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
