basePath: /api/v1
definitions:
  apiv1.PDFGetSignedReply:
    properties:
      data:
        $ref: '#/definitions/model.Document'
    type: object
  apiv1.PDFRevokeReply:
    properties:
      data:
        properties:
          status:
            type: boolean
        type: object
    type: object
  apiv1.PDFSignReply:
    properties:
      data:
        $ref: '#/definitions/v1_sealer.SealReply'
    type: object
  apiv1.PDFSignRequest:
    properties:
      pdf:
        type: string
    required:
    - pdf
    type: object
  apiv1.PDFValidateReply:
    properties:
      data:
        $ref: '#/definitions/v1_validator.ValidateReply'
    type: object
  apiv1.PDFValidateRequest:
    properties:
      pdf:
        type: string
    type: object
  helpers.Error:
    properties:
      details: {}
      title:
        type: string
    type: object
  helpers.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/helpers.Error'
    type: object
  model.Document:
    properties:
      data:
        type: string
      message:
        type: string
      reason:
        type: string
      revoked_at:
        type: integer
      sealer_backend:
        type: string
      transaction_id:
        type: string
    type: object
  v1_sealer.SealReply:
    properties:
      data:
        type: string
      error:
        type: string
      sealer_backend:
        type: string
      transaction_id:
        type: string
    type: object
  v1_validator.ValidateReply:
    properties:
      error:
        type: string
      intact_signature:
        type: boolean
      transaction_id:
        type: string
      valid_signature:
        type: boolean
      validation_backend:
        type: string
    type: object
info:
  contact: {}
  title: Datastore API
  version: 0.1.0
paths:
  /pdf/{transaction_id}:
    get:
      consumes:
      - application/json
      description: fetch a singed pdf
      operationId: pdf-fetch
      parameters:
      - description: transaction_id
        in: path
        name: transaction_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/apiv1.PDFGetSignedReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: fetch singed pdf
      tags:
      - eduseal
  /pdf/revoke/{transaction_id}:
    put:
      consumes:
      - application/json
      description: revoke a singed pdf
      operationId: pdf-revoke
      parameters:
      - description: transaction_id
        in: path
        name: transaction_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/apiv1.PDFRevokeReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: revoke signed pdf
      tags:
      - eduseal
  /pdf/sign:
    post:
      consumes:
      - application/json
      description: sign base64 encoded PDF
      operationId: pdf-sign
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/apiv1.PDFSignRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/apiv1.PDFSignReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Sign pdf
      tags:
      - eduseal
  /pdf/validate:
    post:
      consumes:
      - application/json
      description: validate a signed base64 encoded PDF
      operationId: pdf-validate
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/apiv1.PDFValidateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/apiv1.PDFValidateReply'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Validate pdf
      tags:
      - eduseal
swagger: "2.0"
